
get http://localhost:3000/todos/?priority=HIGH

####

get http://localhost:3000/todos/?status=TO%20DO

#####

get http://localhost:3000/todos/?search_q=Buy

####

get http://localhost:3000/todos/?category=WORK

####

get http://localhost:3000/todos/1/

######

get http://localhost:3000/agenda/?date=04-22-2021

####

post http://localhost:3000/